### PR TITLE
added separate directories for client and server.

### PR DESCRIPTION
**Pull request by mark-sabotta**
Added client README. Moved server README.

### CODE REVIEW

**Comment by ThobiWanKenobi** [comment]
I personally find it a bit weird to run seperate branches for server and client, since this might seriously make things hard for the frontend, since they depend on the backend. I would rather just have 1 branch that is the final product, and every branch is a feature, frontend or backend. But, that is just what I would do. I just find it a bit... Risky, and strange to do it this way :)

**Review by wckliment — COMMENTED** [review]
Approved

**Comment by mark-sabotta** [comment]
Closing the pull request doesn't merge the content. Can you take another look to try to pull the changes into main?

**Review by wckliment — APPROVED** [review]
Approved

**Comment by wckliment** [comment]
Sorry about that. I went ahead and approved it and completed the merge.
  
​
  
  

  
​Chase Kliment
  
​720.545.6079
  
***@***.***

**Pull request merged**
